import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
i18n.use(initReactI18next).init({
  resources: {
    ru: {
      translation: {
        footerAboutUsOurStory: 'Наша история',
        footerReviews: 'Отзывы',
        footerContacts: 'Контакты',
        footerCategories: 'Категории',
        categoryTitle: 'Категории',
        categoryTables: 'Столы',
        categoryChairs: 'Стулья',
        categoryArmChairs: 'Кресла',
        categorySofas: 'Диваны',
        categoryDecor: 'Декор',
        categoryBedding: 'Постельное бельё',
        categoryFinishMaterials: 'Отделочные материалы',
        footerAccount: 'Аккаунт',
        footerSignIn: 'Войти',
        footerRegister: 'Зарегистрироваться',
        footerDesigners: 'Дизайнерам и архитекторам',
        footerWholeSellers: 'Оптовым покупателям',
        headerSearchLabel: 'Поиск...',
        headerButtonAccount: 'Аккаунт',
        headerButtonCart: 'Корзина',
        headerCategoryFurniture: 'Мебель',
        headerCategoryLight: 'Свет',
        headerCategoryDecor: 'Декор',
        headerCategoryHoreca: 'Horeca',
        headerCategoryNewProducts: 'Новые',
        headerCategoryDecorationMaterials: 'Отделочные материалы',
        titleProductPopular: 'Популярные запросы',
        titleAuthorization: 'Войти',
        titleRegistration: 'Зарегистрироваться',
        AuthorizationHelperText: 'Ещё не зарегистрированны?',
        RegistrationHelperText: 'Уже имеется аккаунт?',
        AuthorizationLabelMail: 'Введите ваш Email',
        AuthorizationLabelPassword: 'Введите пароль',
        RegistrationLabelMail: 'Ваш E-mail',
        RegistrationLabelPassword: 'Ваш пароль',
        RegistrationLabelPasswordRepeat: 'Повтоите пароль',
        filterTitle: 'Фильтры',
        filterTitleCategory: 'Категории',
        filterTitleMaterial: 'Материал',
        filterTitleColor: 'Цвет',
        filterTitlePrice: 'Цена',
        filterTitleAscending: 'По возрастанию',
        filterTitleDescending: 'По убыванию',
        filterTitleSort: 'Сортировка',
        detailsButttonAdd: 'В корзину',
      },
    },

    en: {
      translation: {
        footerAboutUsOurStory: 'Our story',
        footerReviews: 'Reviews',
        footerContacts: 'Contacts',
        footerCategories: 'Categories',
        categoryTitle: 'Category',
        categoryTables: 'Tables',
        categoryChairs: 'Chairs',
        categoryArmChairs: 'Armchairs',
        categorySofas: 'Sofas',
        categoryDecor: 'Decor',
        categoryBedding: 'Bedding',
        categoryFinishMaterials: 'Finishing materials',
        footerAccount: 'Account',
        footerSignIn: 'Sign in',
        footerRegister: 'Sign up',
        footerDesigners: 'Designers & Architects',
        footerWholeSellers: 'Wholesalers',
        headerSearchLabel: 'Search...',
        headerButtonAccount: 'Account',
        headerButtonCart: 'Cart',
        headerCategoryFurniture: 'Furniture',
        headerCategoryLight: 'Light',
        headerCategoryDecor: 'Decor',
        headerCategoryHoreca: 'Horeca',
        headerCategoryNewProduct: 'New',
        headerCategoryDecorationMaterials: 'Decoration material',
        titleProductPopular: 'Popular query',
        titleAuthorization: 'Sign in',
        titleRegistration: 'Sign up',
        AuthorizationHelperText: 'Not registered yet?',
        RegistrationHelperText: 'Already have an account?',
        AuthorizationLabelText: 'Enter Email',
        RegistrationLabelText: 'Enter password',
        AuthorizationLabelMail: 'Enter your email',
        AuthorizationLabelPassword: 'Enter your password',
        RegistrationLabelMail: 'Your email',
        RegistrationLabelPassword: 'Your password',
        RegistrationLabelPasswordRepeat: 'Repeat password',
        filterTitle: 'Filters',
        filterTitleCategory: 'Category',
        filterTitleMaterial: 'Material',
        filterTitleColor: 'Color',
        filterTitlePrice: 'Price',
        filterTitleAscending: 'Ascending',
        filterTitleDescending: 'Descending',
        filterTitleSort: 'Sort',
        detailsButttonAdd: 'Add to cart',
      },
    },
  },

  lng: 'ru',
  fallbackLng: 'ru',
});
