import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
i18n.use(initReactI18next).init({
  resources: {
    ru: {
      translation: {
        footerAbouUS: 'О нас',
        footerContacts: 'Контакты',
        titleCompany: 'Компания',
        titlePhone: 'Телефон',
        titleSurname: 'Фамилия',
        titleName: 'Имя',
        titleToGoPayment: 'Перейти к оплате',
        titleSumm: 'Сумма',
        titleCategories: 'Категории',
        titleSubcategories: 'Подкатегории',
        categoryTitle: 'Категории',
        footerSignIn: 'Войти',
        footerRegister: 'Зарегистрироваться',
        footerDesigners: 'Дизайнерам и архитекторам',
        footerWholeSellers: 'Оптовым покупателям',
        headerSearchLabel: 'Поиск...',
        titleAccount: 'Аккаунт',
        titleCart: 'Корзина',
        titleDelete: 'удалить',
        titleFavorite: 'Избраннное',
        titleLanguage: 'Язык',
        titleQuantity: 'Количество',
        titleSafeguards: 'Гарантии',
        titleTotal: 'Итого',
        titleOrder: 'Оформить заказ',
        textSafeguards: 'Доставим в течении 10 - 20 дней',
        titleSelectMaterial: 'Выберите материал',
        titleRecommended: 'Рекомендуется для вас',
        headerCategoryFurniture: 'Мебель',
        headerCategoryLight: 'Свет',
        headerCategoryDecor: 'Декор',
        headerCategoryHoreca: 'Horeca',
        headerCategoryNewProducts: 'Новые',
        headerCategoryDecorationMaterials: 'Отделочные материалы',
        titleProductPopular: 'Популярные запросы',
        titleAuthorization: 'Войти',
        titleRegistration: 'Зарегистрироваться',
        AuthorizationHelperText: 'Ещё не зарегистрированны?',
        RegistrationHelperText: 'Уже имеется аккаунт?',
        AuthorizationLabelMail: 'Введите Email',
        AuthorizationLabelPassword: 'Введите пароль',
        RegistrationLabelMail: 'Ваш E-mail',
        RegistrationLabelPassword: 'Ваш пароль',
        RegistrationLabelPasswordRepeat: 'Повтоите пароль',
        filterTitle: 'Фильтры',
        filterTitleReset: 'Сбросить фильтры',
        filterTitleCategory: 'Категории',
        filterTitleMaterial: 'Материал',
        filterTitleColor: 'Цвет',
        filterTitlePrice: 'Цена',
        filterTitleAscending: 'По возрастанию',
        filterTitleDescending: 'По убыванию',
        filterTitleSort: 'Сортировка',
        detailsButttonAdd: 'Добавить в корзину',
        authMessageErrorRequire: 'необходимо заполнить!',
        authMessageErrorPasswordMatch: 'пароли не совпадают',
        authMessageErrorMail: 'вы забыли указать почту',
        authMessageErrorMinLength:
          'пароль должен состоять не менее чем из 8 символов',
        authMessageErrorMaxLength:
          'пароль должен состоять не более чем из 14 символов',
        authMessageErrorStringAndInt:
          'Пароль должен содержать как минимум одну латинскую букву и одну цифру, без использования специальных символов',
        accountMenuProfile: 'профиль',
        accountMenuLogout: 'выйти',
      },
    },

    en: {
      translation: {
        footerAboutUsOurStory: 'Our story',
        footerReviews: 'Reviews',
        footerContacts: 'Contacts',
        titleCompany: 'Company',
        titlePhone: 'Phone',
        titleSurname: 'Surname',
        titleName: 'Name',
        titleToGoPayment: 'Proceed to payment',
        titleSumm: 'Amount',
        footerCategories: 'Categories',
        footerSubcategories: 'Subcategories',
        categoryTitle: 'Category',
        footerSignIn: 'Sign in',
        footerRegister: 'Sign up',
        footerDesigners: 'Designers & Architects',
        footerWholeSellers: 'Wholesalers',
        headerSearchLabel: 'Search...',
        titleAccount: 'Account',
        titleCart: 'Cart',
        titleDelete: 'delete',
        titleFavorite: 'Favorite',
        titleLanguage: 'Language',
        titleQuantity: 'Quantity',
        titleSafeguards: 'Safeguards',
        titleTotal: 'Total',
        titleOrder: 'Place an order',
        textSafeguards: '10 to 20 days for delivery',
        titleSelectMaterial: 'Select material',
        titleRecommended: 'Recommended products',
        headerCategoryFurniture: 'Furniture',
        headerCategoryLight: 'Light',
        headerCategoryDecor: 'Decor',
        headerCategoryHoreca: 'Horeca',
        headerCategoryNewProduct: 'New',
        headerCategoryDecorationMaterials: 'Decoration material',
        titleProductPopular: 'Popular query',
        titleAuthorization: 'Sign in',
        titleRegistration: 'Sign up',
        titleCategories: 'Categories',
        titleSubcategories: 'Subcategories',
        AuthorizationHelperText: 'Not registered yet?',
        RegistrationHelperText: 'Already have an account?',
        AuthorizationLabelText: 'Enter Email',
        RegistrationLabelText: 'Enter password',
        AuthorizationLabelMail: 'Enter email',
        AuthorizationLabelPassword: 'Enter your password',
        RegistrationLabelMail: 'Your email',
        RegistrationLabelPassword: 'Your password',
        RegistrationLabelPasswordRepeat: 'Repeat password',
        filterTitle: 'Filters',
        filterTitleReset: 'Reset filters',
        filterTitleCategory: 'Category',
        filterTitleMaterial: 'Material',
        filterTitleColor: 'Color',
        filterTitlePrice: 'Price',
        filterTitleAscending: 'Ascending',
        filterTitleDescending: 'Descending',
        filterTitleSort: 'Sort',
        detailsButttonAdd: 'Add to cart',
        authMessageErrorRequire: 'This is a required field!',
        authMessageErrorPasswordMatch: "passwords don't match",
        authMessageErrorMail: 'You forgot to specify "@mail.ru"',
        authMessageErrorMinLength:
          'Password must be at least 8 characters long',
        authMessageErrorMaxLength:
          'Password must be at most 14 characters long',
        authMessageErrorStringAndInt:
          'The password must contain at least one Latin letter and one number, without using special characters',
        accountMenuProfile: 'profile',
        accountMenuLogout: 'logout',
      },
    },
  },

  lng: 'ru',
  fallbackLng: 'ru',
});
